# Use a imagem oficial do PostgreSQL
FROM postgres:latest

# Definir variáveis de ambiente para configuração do PostgreSQL
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin123
ENV POSTGRES_DB=satisfaction_db

# Exponha a porta padrão do PostgreSQL
EXPOSE 5432

# O PostgreSQL será executado automaticamente quando o container iniciar