# Usar a imagem oficial do Node.js versão 22
FROM node:22

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o package.json e o package-lock.json para instalar dependências
COPY package*.json ./

# Instalar as dependências
RUN npm install

# Copiar o restante do código da aplicação
COPY . .

# Expor a porta que o Node.js irá utilizar
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "start"]