# Use a imagem oficial do MongoDB
FROM mongo:latest

# Definir variáveis de ambiente para configuração do MongoDB
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=admin123
ENV MONGO_INITDB_DATABASE=satisfaction_db

# Expor a porta padrão do MongoDB
EXPOSE 27017

# O MongoDB será iniciado automaticamente