version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: satisfaction_db
    ports:
      - "5432:5432"
    networks:
      - app_network

  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: satisfaction_db
    ports:
      - "27017:27017"
    networks:
      - app_network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: nodejs_container
    environment:
      DB_POSTGRES_HOST: postgres
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USER: admin
      DB_POSTGRES_PASSWORD: admin123
      DB_POSTGRES_NAME: satisfaction_db
      DB_MONGO_HOST: mongo
      DB_MONGO_PORT: 27017
      DB_MONGO_USER: admin
      DB_MONGO_PASSWORD: admin123
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - postgres
      - mongo

networks:
  app_network:
    driver: bridge